### ISSUE TITLE
images not displaying on iOS

### ISSUE THREAD

**Issue by constemi** [benawad/react-native-image-caching#3]
fantastic method! I have an expo project so I figured I would give it a try.
Works flawlessly on Android and it does work on iOS, it caches and reads back but `<Image source={} />` and actually displaying it via the path is where it goes south.

Did some research and made a few very minor tweaks recommended by others
-  add isStatic: true -> to source : { } (undocumented *no longer used it turns out*)
-  ensuring a width and height are both set in style.
-  set width and height properties inside source
-  ensure paths are prefixed with file:/// which is how it works normally

https://snack.expo.io/rkdxpLb7m

I'd love to get this working on both sides if anyone is trying their hand at this and has some success please let me know.

**Comment by benawad** [comment]
I made another version that I think works on ios and android: https://github.com/benawad/Picache

What does isStatic do?

**Comment by constemi** [comment]
it currently does nothing, turns out it was removed. 
https://github.com/facebook/react-native/commit/5b425278bb849ec03912fd155a20456890d14f82

Thanks for the reply I'll try it out!
