### ISSUE TITLE
Images don't load

### ISSUE THREAD

**Issue by zRelux** [benawad/react-native-image-caching#4]
It doesn't load the images it just says loaded image from cache but the image doesn't show up

**Comment by benawad** [comment]
what device did you test on?

**Comment by zRelux** [comment]
Expo Client on IPhone 6

**Comment by zRelux** [comment]
The images get to the cache but they don't render

**Comment by benawad** [comment]
I made a new package that works with both ios and android: https://github.com/benawad/Picache
